import { describe, expect, test } from "bun:test";
import { effectiveLeadCount, formatTaskPrompt, parsePlanResponse, type PlanResponse } from "./prompts.ts";
import planFixture from "../fixtures/orchestrator-cli-plan-response.json";

function plan(leads: number): PlanResponse {
	return {
		plan_id: "p1",
		run_id: "r1",
		task_class: "implementation",
		complexity: 5,
		risk: "medium",
		topology: { depth: 1, leads, workers: 0, shape: "single" },
		route: {
			selected: { capability: "lead", effort: "standard", verification_depth: "targeted" },
			recommended: { capability: "lead", effort: "standard", verification_depth: "targeted" },
			mode: "adaptive",
			history_sufficient: true,
			explanation: {},
		},
		effective_quality_floor: 0.8,
		cost_aggressiveness: 0.5,
	};
}

describe("core/prompts.ts effectiveLeadCount", () => {
	test("clamps to the given maxLeads ceiling, defaulting to 8", () => {
		expect(effectiveLeadCount(plan(20))).toBe(8);
		expect(effectiveLeadCount(plan(20), 4)).toBe(4);
	});

	test("non-finite lead counts fall back to 1", () => {
		expect(effectiveLeadCount(plan(Number.NaN))).toBe(1);
	});
});

describe("core/prompts.ts formatTaskPrompt", () => {
	test("includes the retry note only on a retry", () => {
		const base = formatTaskPrompt({ taskId: "t1", capability: "worker", task: "do it" }, "run-1");
		expect(base).not.toContain("Retry context");
		const retry = formatTaskPrompt({ taskId: "t1", capability: "worker", task: "do it", retryOf: "t0", retryCount: 1 }, "run-1");
		expect(retry).toContain("Retry context: this is retry #2");
	});

	test("appends operator messages when present", () => {
		const withMsg = formatTaskPrompt({ taskId: "t1", capability: "worker", task: "do it" }, "run-1", ["stop early"]);
		expect(withMsg).toContain("stop early");
		expect(withMsg).toContain("User messages while this run was in progress");
	});
});

describe("core/prompts.ts parsePlanResponse", () => {
	test("accepts a valid plan and returns it unchanged", () => {
		const valid = plan(3);
		expect(parsePlanResponse(valid)).toEqual(valid);
	});

	test("rejects a plan missing a required field, naming it", () => {
		const invalid = plan(3) as unknown as Record<string, unknown>;
		delete invalid.task_class;
		expect(() => parsePlanResponse(invalid)).toThrow(/task_class/);
	});

	test("rejects a plan whose field has the wrong type, naming it", () => {
		const invalid = plan(3) as unknown as Record<string, unknown>;
		invalid.complexity = "five";
		expect(() => parsePlanResponse(invalid)).toThrow(/complexity/);
	});

	test("rejects a plan with a missing nested topology field, naming it", () => {
		const invalid = plan(3) as unknown as { topology: Record<string, unknown> };
		delete invalid.topology.leads;
		expect(() => parsePlanResponse(invalid)).toThrow(/topology\.leads/);
	});

	test("rejects a non-object value", () => {
		expect(() => parsePlanResponse(null)).toThrow(/plan response/i);
		expect(() => parsePlanResponse("nope")).toThrow(/plan response/i);
	});

	test("parses a real `orchestrator.cli plan` JSON response captured from the Python CLI (fixtures/orchestrator-cli-plan-response.json)", () => {
		// Generated by running the exact command `adapters/orchestrator-cli.ts`'s `planRun` invokes,
		// from the repo root, against a fresh, empty `CODING_AGENT_ORCHESTRATOR_HOME`:
		//
		//   PYTHONPATH=<repo> CODING_AGENT_ORCHESTRATOR_HOME=$(mktemp -d) \
		//     python3 -m orchestrator.cli plan ht-orch-1700000000000-fixture001 bugfix 5 medium
		//
		// (<repo> = the absolute path to this checkout's repo root, i.e. `$(pwd)` when run from
		// there.) Re-run to reproduce: this fixture's `run_id` was pinned as a CLI argument, and
		// the CLI is otherwise deterministic given an empty history store, so the JSON this prints
		// is byte-for-byte identical to fixtures/orchestrator-cli-plan-response.json — confirmed by
		// re-running it and diffing (no volatile timestamp/id fields turned up in this output; the
		// CLI's only non-deterministic-looking field, `plan_id`, is actually a deterministic hash of
		// the pinned inputs, so it matched too). The Python CLI emits many fields `PlanResponse`
		// doesn't need (`topology_recommendation`, `policy`, `features`, `feature_inventory`, ...) —
		// this pins that `parsePlanResponse` tolerates the extras and still extracts exactly the
		// fields the pipeline reads.
		const fixture = planFixture as unknown as Record<string, unknown>;
		const result = parsePlanResponse(fixture);
		const routeFixture = fixture.route as Record<string, unknown>;
		expect(result).toEqual({
			plan_id: "448e996857a25649",
			run_id: "ht-orch-1700000000000-fixture001",
			task_class: "bugfix",
			complexity: 5,
			risk: "medium",
			topology: { depth: 2, leads: 1, workers: 2, shape: "single_lead" },
			route: {
				selected: { capability: "implementation_fast", effort: "low", verification_depth: "targeted" },
				recommended: { capability: "implementation_strong", effort: "high", verification_depth: "full" },
				mode: "recommend",
				history_sufficient: false,
				explanation: routeFixture.explanation as Record<string, unknown>,
			},
			effective_quality_floor: 0.97,
			cost_aggressiveness: 0.7,
		});
		expect(effectiveLeadCount(result)).toBe(1);
	});
});
